Folosiți codul de la Exemplul 1.11 într-o metodă care are ca parametru int x și
returnează 10/x. Metoda trebuie sa returneze rezultatul operatiei si sa anunte situatia unei impartiti la
0. Apelați metoda. Metoda tratează excepția în corpul ei sau o aruncă, la declarare. Observați diferența
de abordare. Care este mai flexibilă ?

Exemplul 1.11 

public static void main(String[] args) {
int a;
int b;
a = 1;
try {
b = 10/a;
} catch (ArithmeticException e) {
System.out.println("Impartire prin 0. b=0");
b = 0;
e.printStackTrace();
}
catch (Exception e) {
b = -1;
System.out.println("Eroare generala");
e.printStackTrace();
}
System.out.print("b="+b);
}